/* spell-checker: disable */
const knownAliases = new Map([
	["a-button", "a-button-blood-type"],
	["ab-button", "ab-button-blood-type"],
	["b-button", "b-button-blood-type"],
	["blue-circle", "large-blue-circle"],
	["blue-square", "large-blue-square"],
	["brown-circle", "large-brown-circle"],
	["brown-square", "large-brown-square"],
	["bullseye", "direct-hit"],
	["eight-o-clock", "eight-oclock"],
	["eleven-o-clock", "eleven-oclock"],
	["enraged-face", "pouting-face"],
	["face-with-crossed-out-eyes", "dizzy-face"],
	["five-o-clock", "five-oclock"],
	["flag-cocos-islands", "flag-cocos-keeling-islands"],
	["flag-cote-d-ivoire", "flag-cote-divoire"],
	["flag-myanmar", "flag-myanmar-burma"],
	["flag-u-s-outlying-islands", "flag-us-outlying-islands"],
	["flag-u-s-virgin-islands", "flag-us-virgin-islands"],
	["four-o-clock", "four-oclock"],
	["ginger-root", "ginger"],
	["green-circle", "large-green-circle"],
	["green-square", "large-green-square"],
	["keycap-0", "keycap-digit-zero"],
	["keycap-1", "keycap-digit-one"],
	["keycap-2", "keycap-digit-two"],
	["keycap-3", "keycap-digit-three"],
	["keycap-4", "keycap-digit-four"],
	["keycap-5", "keycap-digit-five"],
	["keycap-6", "keycap-digit-six"],
	["keycap-7", "keycap-digit-seven"],
	["keycap-8", "keycap-digit-eight"],
	["keycap-9", "keycap-digit-nine"],
	["man-s-shoe", "mans-shoe"],
	["men-s-room", "mens-room"],
	["nine-o-clock", "nine-oclock"],
	["o-button", "o-button-blood-type"],
	["one-o-clock", "one-oclock"],
	["orange-circle", "large-orange-circle"],
	["orange-square", "large-orange-square"],
	["purple-circle", "large-purple-circle"],
	["purple-square", "large-purple-square"],
	["red-circle", "large-red-circle"],
	["red-exclamation-mark", "exclamation-mark"],
	["red-question-mark", "question-mark"],
	["red-square", "large-red-square"],
	["rescue-worker-s-helmet", "rescue-workers-helmet"],
	["seven-o-clock", "seven-oclock"],
	["six-o-clock", "six-oclock"],
	["smiling-face-with-open-hands", "hugging-face"],
	["ten-o-clock", "ten-oclock"],
	["three-o-clock", "three-oclock"],
	["twelve-o-clock", "twelve-oclock"],
	["two-o-clock", "two-oclocktime"],
	["water-pistol", "pistol"],
	["woman-s-boot", "womans-boot"],
	["woman-s-clothes", "womans-clothes"],
	["woman-s-hat", "womans-hat"],
	["woman-s-sandal", "womans-sandal"],
	["women-s-room", "womens-room"],
	["yellow-circle", "large-yellow-circle"],
	["yellow-square", "large-yellow-square"],
]);
/* spell-checker: enable */

export function getEmojipediaSlug(unicodeSlug: string) {
	return knownAliases.get(unicodeSlug) ?? unicodeSlug;
}
